### ISSUE TITLE
PHP updated to 7 now its broken

### ISSUE THREAD

**Issue by waynemillskidals** [octivi/yealink-phonebook#11]
We updated to PHP7 as we now get this error

Any ideas? is it compatible with PHP7?

`[Mon Apr 09 12:14:16.802334 2018] [:error] [pid 23635] [client 77.76.73.254:60591] PHP Fatal error:  Uncaught Error: Call to undefined function Octivi\\Service\\simplexml_load_string() in phar:///var/www/domains/fuse2.net/yealinkpb/foams4sport/yealink-phonebook.phar/src/Octivi/Service/XMLFileService.php:44\nStack trace:\n#0 phar:///var/www/domains/fuse2.net/yealinkpb/foams4sport/yealink-phonebook.phar/src/Octivi/Controller/ContactController.php(133): Octivi\\Service\\XMLFileService->loadFile()\n#1 phar:///var/www/domains/fuse2.net/yealinkpb/foams4sport/yealink-phonebook.phar/src/Octivi/Controller/ContactController.php(34): Octivi\\Controller\\ContactController->generateFormModel('contacts.xml')\n#2 [internal function]: Octivi\\Controller\\ContactController->indexAction(Object(Symfony\\Component\\HttpFoundation\\Request), 'contacts.xml')\n#3 phar:///var/www/domains/fuse2.net/yealinkpb/foams4sport/yealink-phonebook.phar/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(126): call_user_func_array(Array, Array)\n#4 phar:///var/www/domains/fuse2.net/yealinkpb/foams4sport/yealink-phonebook.phar/vendor/symfony/ in phar:///var/www/domains/fuse2.net/yealinkpb/foams4sport/yealink-phonebook.phar/src/Octivi/Service/XMLFileService.php on line 44
[Mon Apr 09 12:15:01.759825 2018] [:error] [pid 23634] [client 77.76.73.254:60609] PHP Fatal error:  Uncaught Error: Call to undefined function Octivi\\Service\\simplexml_load_string() in phar:///var/www/domains/fuse2.net/yealinkpb/foams4sport/yealink-phonebook.phar/src/Octivi/Service/XMLFileService.php:44\nStack trace:\n#0 phar:///var/www/domains/fuse2.net/yealinkpb/foams4sport/yealink-phonebook.phar/src/Octivi/Controller/ContactController.php(133): Octivi\\Service\\XMLFileService->loadFile()\n#1 phar:///var/www/domains/fuse2.net/yealinkpb/foams4sport/yealink-phonebook.phar/src/Octivi/Controller/ContactController.php(34): Octivi\\Controller\\ContactController->generateFormModel('contacts.xml')\n#2 [internal function]: Octivi\\Controller\\ContactController->indexAction(Object(Symfony\\Component\\HttpFoundation\\Request), 'contacts.xml')\n#3 phar:///var/www/domains/fuse2.net/yealinkpb/foams4sport/yealink-phonebook.phar/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(126): call_user_func_array(Array, Array)\n#4 phar:///var/www/domains/fuse2.net/yealinkpb/foams4sport/yealink-phonebook.phar/vendor/symfony/ in phar:///var/www/domains/fuse2.net/yealinkpb/foams4sport/yealink-phonebook.phar/src/Octivi/Service/XMLFileService.php on line 44 
`

**Comment by mosidze** [comment]
Same problem- i try to use binary and git version- same problem, does not loading.

**Comment by thijsvdc** [comment]
Same issue here, using PHP 7.0.30-0ubuntu0.16.04.1

**Comment by svdwalt007** [comment]
Sane same

**Comment by MysticalByte** [comment]
Fixed this by installing mbstring and xml on my debian 9 with php 7.0
apt-get install php-mbstring
apt-get install php-xml

**Comment by MarvinMynx** [comment]
Didn't fixed it for me. Had php-mbstring and php-xml already installed in the latest version on my Ubuntu 16.04.6 LTS with PHP 7.2.
Both Versions Git Clone => Composer and the latest release are still broken for me.
```
( ! ) Fatal error: Uncaught Error: Call to undefined function Octivi\Service\simplexml_load_string() in phar:///var/www/html/ypb/yealink-phonebook.phar/src/Octivi/Service/XMLFileService.php on line 44
( ! ) Error: Call to undefined function Octivi\Service\simplexml_load_string() in phar:///var/www/html/ypb/yealink-phonebook.phar/src/Octivi/Service/XMLFileService.php on line 44
Call Stack
#	Time	Memory	Function	Location
1	0.0003	395336	{main}( )	.../index.php:0
2	0.0003	397296	require_once( '/var/www/html/ypb/yealink-phonebook.phar' )	.../index.php:17
3	0.0790	1926400	include( 'phar:///var/www/html/ypb/yealink-phonebook.phar/index.php' )	.../yealink-phonebook.phar:9
4	0.0790	1926640	require_once( 'phar:///var/www/html/ypb/yealink-phonebook.phar/web/index.php' )	.../index.php:3
5	0.0812	2025152	Silex\Application->run( )	.../index.php:10
6	0.0816	2113112	Silex\Application->handle( )	.../Application.php:493
7	0.0833	2207544	Symfony\Component\HttpKernel\HttpKernel->handle( )	.../Application.php:516
8	0.0833	2207544	Symfony\Component\HttpKernel\HttpKernel->handleRaw( )	.../HttpKernel.php:66
9	0.0901	2499664	call_user_func_array:{phar:///var/www/html/ypb/yealink-phonebook.phar/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php:126} ( )	.../HttpKernel.php:126
10	0.0902	2500072	Octivi\Controller\ContactController->indexAction( )	.../HttpKernel.php:126
11	0.0902	2500072	Octivi\Controller\ContactController->generateFormModel( )	.../ContactController.php:34
12	0.0913	2501384	Octivi\Service\XMLFileService->loadFile( )	.../ContactController.php:133
```
phpver
```
/etc/php/7.2/apache2/conf.d/20-simplexml.ini, /etc/php/7.2/apache2/conf.d/20-sockets.ini, 
Simplexml support | enabled
-- | --
Revision | $Id: 341daed0ee94ea8f728bfd0ba4626e6ed365c0d1 $
Schema support | enabled
SimpleXML | Sterling Hughes, Marcus Boerger, Rob Richards
-- | --
```

**Comment by HigeMynx** [comment]
`

( ! ) Fatal error: Uncaught Error: Call to undefined function Octivi\Service\simplexml_load_string() in phar:///var/www/html/ypb/yealink-phonebook.phar/src/Octivi/Service/XMLFileService.php on line 44
--


`
