### ISSUE TITLE
Can't add * or # to phonebook number

### ISSUE THREAD

**Issue by Joohansson** [octivi/yealink-phonebook#13]
That is needed for some feature codes like *43 or *78. I would like to have them in phonebook. It's possible to edit the xml manually and it works in the phone so I don't see any problem there. It's a limitation on the php site.

**Comment by esoare** [comment]
I see it has something to do with there being a charcode Validation.

Orginal Code:

(var isNumberValidator = function (evt) {
    evt = (evt) ? evt : window.event;
    var charCode = (evt.which) ? evt.which : evt.keyCode;
    if (charCode > 31 && (charCode < 48 || charCode > 57) && charCode != 43) {
        return false;
    }
    return true;)

[https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_event_key_charcode](url)
Shows that '*' is 42.

Code I tried:
(var isNumberValidator = function (evt) {
    evt = (evt) ? evt : window.event;
    var charCode = (evt.which) ? evt.which : evt.keyCode;
    if (charCode > 31 && (charCode < 42 || charCode > 57) && charCode != 43) { 
        return false;
    })
I edited this at the .phar level.

But I get an error with the SHA1 signature being broken. 
 
( 
Fatal error: Uncaught PharException: phar "/homepages/37/d520364955/htdocs/PhoneBookW60B_for_Parking_asdasjdlkajsdklajsd/yealink-phonebook.phar" SHA1 signature could not be verified: broken signature in /homepages/37/d520364955/htdocs/PhoneBookW60B_for_Parking_asdasjdlkajsdklajsd/yealink-phonebook.phar:8 Stack trace: #0 /homepages/37/d520364955/htdocs/PhoneBookW60B_for_Parking_asdasjdlkajsdklajsd/yealink-phonebook.phar(8): Phar::webPhar(NULL, 'index.php') #1 /homepages/37/d520364955/htdocs/PhoneBookW60B_for_Parking_asdasjdlkajsdklajsd/index.php(17): require_once('/homepages/37/d...') #2 {main} thrown in /homepages/37/d520364955/htdocs/PhoneBookW60B_for_Parking_asdasjdlkajsdklajsd/yealink-phonebook.phar on line 8
)

a: Not sure if changing the code to 42 would allow for the ' * ' to be added
b: Not sure how to fix the SHA1 signature error.
