### ISSUE TITLE
create a new phar file

### ISSUE THREAD

**Issue by xciser77** [octivi/yealink-phonebook#15]
I extracted the phar file to made some changes to let i work with a other brand of phones. 
Now I would like to create a new phar file, but how can I do this the right way ?

**Comment by MarvinMynx** [comment]
Sorry, I don't know about the phar file but did you get the web interface (PHP) up and running?
If so, how did you do this? Because I keep getting errors with PHP 7.2 and Ubuntu 16.04.6 LTS
