### ISSUE TITLE
Zip files appear muddled

### ISSUE THREAD

**Issue by cjward** [octivi/yealink-phonebook#9]
Hi
I have downloaded the zip files but have encountered a number of issues.
The original file downloaded was titled yealink-phonebook-master.zip  this extracts, with an impressive file structure, but I cannot get it to run. it looks in the index.php then hangs on a white screen.
Next I tried yealink-phonebook-ver1.0.zip (which extracts same structure as the tar.gz). This extracted with a much less impressive file structure. The index.php loads and then calls for SERVER/contac/contact.xml   -  that folder does not exist. if I rename pb folder to contact then it loads contact.xml with the warning that no file is associated with it.
I have tried a few variations by renaming and trying to build a folder structure that works, I can get as far as it looking for a folder or file, named source but that is it.
Am I being a bit dense or missing something?
Help!

**Comment by MarvinMynx** [comment]
Having the same issue. Even the other way using git clone, curl and composer isn't functioning.
Anyone here to help?
